const ORDER_STATUS = {
  SUCCESS: {
    PAYMENT: "PAYMENT AUTHORIZED",
    ACCOUNT: "ACCOUNT CREATED",
    PAYMENT_METHOD: "PAYMENT METHOD ADDED",
    BILLING_GROUP: "BILLING GROUP ADDED",
    SUBSCRIPTION: "SUBSCRIPTION ADDED",
    OK: "OK",
  },
  FAILURE: {
    PAYMENT: "ADEYN FLOW FAILED",
    ACCOUNT: "ACCOUNT CREATE FLOW FAILED",
    PAYMENT_METHOD: "PAYMENT METHOD ADDITION FAILED",
    BILLING_GROUP: "BILLING GROUP FAILED",
    SUBSCRIPTION: "SUBSCRIPTION FAILED",
    DEFAULT_SUBSCRIPTION: "DEFAULT SUBSCRIPTION FAILED",
  },
};

module.exports = { ORDER_STATUS };
